/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Joel
 */
public class PrecificadorTUS extends javax.swing.JFrame {

    /**
     * Creates new form PrecificadorTUS
     */
    public PrecificadorTUS() {
        initComponents();
        pan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFornos = new javax.swing.JSpinner();
        txtDias = new javax.swing.JSpinner();
        txtParc = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValorPorForno = new javax.swing.JLabel();
        lblValorParcela = new javax.swing.JLabel();
        lblEstImposto = new javax.swing.JLabel();
        lblAliHosp = new javax.swing.JLabel();
        lblLog = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        sliA = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl30ddl = new javax.swing.JLabel();
        chkDesc = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cotação online TUS v.2 by Joel R M Reis");

        txtFornos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFornos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        txtDias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDias.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtParc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtParc.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 10.0d, 1.0d));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Qtd de Fornos?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Qtd de dias?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Pgto em quantas parcelas?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor por Forno");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor Total à Prazo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Valor da parcela");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Estimativa de Imposto");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Alimentação + hospedagem");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Logística");

        lblValorPorForno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorPorForno.setText("                            ");

        lblValorParcela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorParcela.setText("                            ");

        lblEstImposto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstImposto.setText("                            ");

        lblAliHosp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAliHosp.setText("                            ");

        lblLog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLog.setText("                            ");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setText("                            ");

        sliA.setMinorTickSpacing(1);
        sliA.setOrientation(javax.swing.JSlider.VERTICAL);
        sliA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliAStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Remuneração Mão de Obra");

        lblA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Valor 30ddl");

        lbl30ddl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl30ddl.setText("                           ");

        chkDesc.setText("Desconto para novo Cliente");
        chkDesc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkDescStateChanged(evt);
            }
        });
        chkDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDescActionPerformed(evt);
            }
        });
        chkDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chkDescKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorPorForno)
                    .addComponent(lblValorParcela)
                    .addComponent(lblEstImposto)
                    .addComponent(lblAliHosp)
                    .addComponent(lblLog)
                    .addComponent(lbl30ddl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addGap(70, 70, 70)
                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblA, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sliA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(chkDesc))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbl30ddl, lblAliHosp, lblEstImposto, lblLog, lblTotal, lblValorParcela, lblValorPorForno});

        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)
                        .addComponent(sliA, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11)
                                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorParcela)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lblEstImposto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(lblAliHosp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lblLog))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(panLayout.createSequentialGroup()
                                .addComponent(lblValorPorForno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(lbl30ddl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotal)
                                    .addComponent(chkDesc))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbl30ddl, lblAliHosp, lblEstImposto, lblLog, lblTotal, lblValorParcela, lblValorPorForno});

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/favicon.png"))); // NOI18N
        jButton1.setText("Calcular ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Proposta de Cotação de TUS (Thermal Uniformity Survey - CQI-9)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtParc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFornos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFornos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pan.setVisible(true);
        
        //Formatação para R$
        Locale localeBR = new Locale("pt","BR");
        NumberFormat inteiro = NumberFormat.getInstance();
        NumberFormat dinheiro = NumberFormat.getCurrencyInstance(localeBR);
        NumberFormat percentual = NumberFormat.getPercentInstance(localeBR);
        NumberFormat numberFormat = NumberFormat.getNumberInstance(localeBR);
    

            if (chkDesc.isSelected()){
        sliA.setValue((int)((31.667*(int)txtFornos.getValue()) - 26.667));              //Desconto Cliente Novo, tirando remuneração Engenheiro
           }else {
           }
        
        
        Custos c = new Custos((int)txtFornos.getValue(),(int)txtDias.getValue(),(double)txtParc.getValue(), 5.4f, (float)sliA.getValue()); //Custos(int qtdTus, int dia, double parc, float pDollar)
        Depreciacao s = new Depreciacao((int)txtFornos.getValue(),(int)txtDias.getValue(),(double)txtParc.getValue(), 5.4f, (float)sliA.getValue());
        

       //    if (chkDesc.isSelected()){
       // sliA.setValue((int)c.getRemAut());              //Desconto Cliente Novo, tirando remuneração Engenheiro
       //    }else {
       //    }
        
        s.calcDep();   //Calcular Depreciação f(dollar).
        
        c.CalcCustoTus();
        c.CalcHosp();
        c.CalcLog();
        //c.CalcDesc();
        c.CalcPreco();
        c.calcPgto();
        c.calcImp();

        
        System.out.println("Depreciação por TUS: " + dinheiro.format(s.getDepPorTus()));
        System.out.println("Custo por TUS: " + dinheiro.format(c.getCustoPorTus()));
        //System.out.println("Preço do TUS: " + ((s.getDepPorTus() + c.getCustTus())));
        System.out.println("Preço do Tus: " + dinheiro.format(c.getPreco()));
        System.out.println("Total à Prazo: " + dinheiro.format(c.getCustTotalPrazo()));
        System.out.println("Valor da parcela: " + dinheiro.format(c.getValorParcela()));
        System.out.println("30ddl: " + dinheiro.format(c.getValor30ddl()));
        System.out.println("Estimativa Imposto: " + dinheiro.format(c.getSimples()));
        System.out.println("Custo da hospedagem + alimentaçã: " + dinheiro.format(c.getHosp()));
        System.out.println("Custo de Logística: " + dinheiro.format(c.getCustLog()));
        System.out.println("Desc " + c.getDescIncond());
        


        lblValorPorForno.setText(dinheiro.format(c.getPreForno()));
        lblValorParcela.setText(dinheiro.format(c.getValorParcela()));
        lblEstImposto.setText(dinheiro.format(c.getSimples()));
        lblAliHosp.setText (dinheiro.format(c.getHosp()));
        lblLog.setText (dinheiro.format(c.getCustLog()));
        lbl30ddl.setText(dinheiro.format(c.getValor30ddl()));
        lblTotal.setText (dinheiro.format(c.getCustTotalPrazo()));
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sliAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliAStateChanged
        // TODO add your handling code here:
        lblA.setText(Integer.toString(sliA.getValue()));
    }//GEN-LAST:event_sliAStateChanged

    private void chkDescStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkDescStateChanged

    }//GEN-LAST:event_chkDescStateChanged

    private void chkDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDescActionPerformed

    }//GEN-LAST:event_chkDescActionPerformed

    private void chkDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkDescKeyTyped

        
    }//GEN-LAST:event_chkDescKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrecificadorTUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrecificadorTUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrecificadorTUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrecificadorTUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrecificadorTUS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkDesc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl30ddl;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAliHosp;
    private javax.swing.JLabel lblEstImposto;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValorParcela;
    private javax.swing.JLabel lblValorPorForno;
    private javax.swing.JPanel pan;
    private javax.swing.JSlider sliA;
    private javax.swing.JSpinner txtDias;
    private javax.swing.JSpinner txtFornos;
    private javax.swing.JSpinner txtParc;
    // End of variables declaration//GEN-END:variables
}
